# Site settings
title: Ubuntu Essentials Guide
description: Introduction to Linux Desktop Environment

# Theme
show_downloads: false
theme: jekyll-theme-cayman

# GitHub settings
github:
  is_project_page: false
